[tool.commitizen]
major_version_zero = true
name = "cz_conventional_commits"
tag_format = "v$major.$minor.$patch$prerelease"
update_changelog_on_bump = true
version_provider = "cargo"
version_scheme = "semver"
