name: Python Chores

on: [push, pull_request]

jobs:
  lint-and-check:
    name: Build (${{ matrix.os }})

    strategy:
      matrix:
          os: [ubuntu-latest, macos-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4
      - name: Ruff Format
        uses: chartboost/ruff-action@v1
        with:
          args: "format ./pyproject.toml"

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Install the project
        run: uv sync --all-extras --dev

      - name: Maturin Build
        uses: PyO3/maturin-action@v1
        with:
          command: build
          args: --release

  publish:
    needs: lint-and-check
    runs-on: ubuntu-latest
    if: "startsWith(github.event.head_commit.message, 'bump:')"
    steps:
      - uses: actions/checkout@v4
      - name: Publish
        uses: PyO3/maturin-action@v1
        env:
          MATURIN_PYPI_TOKEN: "${{ secrets.PYPI_TOKEN }}"
        with:
          command: publish
